/**
 * Deterministic SVG placeholder images, generated by the API.
 *
 * WHY NOT picsum/unsplash: external image hosts need network, rate-limit you,
 * and break the moment a participant is on hotel wifi. These are generated
 * from a hash of the filename, so the same product always gets the same
 * picture, and they cost nothing to serve.
 *
 *   /api/images/<name>.svg?w=600&h=600
 *   &delay=400   artificially slow — Session 9's lazy-loading lab needs this
 *                to be visibly worth doing.
 */
import { Router } from 'express';

const router = Router();

const PALETTES = [
  ['#0f172a', '#334155'], ['#1e3a5f', '#2563eb'], ['#134e4a', '#0d9488'],
  ['#3f2d1a', '#b45309'], ['#4a1d3f', '#be185d'], ['#1c3a1c', '#15803d'],
  ['#3b1f47', '#7c3aed'], ['#4a2019', '#dc2626'], ['#1a3a44', '#0891b2'],
  ['#42331a', '#ca8a04'],
];

function hash(str) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i += 1) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return Math.abs(h);
}

function buildSvg(name, w, h) {
  const seed = hash(name);
  const [from, to] = PALETTES[seed % PALETTES.length];
  const angle = seed % 360;
  const label = name.replace(/-\d+$/, '').replace(/-/g, ' ').slice(0, 26);
  const initials = label.split(' ').filter(Boolean).slice(0, 2).map((w2) => w2[0].toUpperCase()).join('');
  // A few deterministic blobs so images aren't flat rectangles.
  const blobs = Array.from({ length: 3 }, (_, i) => {
    const s = hash(`${name}:${i}`);
    return `<circle cx="${s % w}" cy="${(s >> 8) % h}" r="${40 + ((s >> 16) % Math.floor(Math.min(w, h) / 2))}" fill="#ffffff" opacity="0.05"/>`;
  }).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${label}">
  <defs><linearGradient id="g" gradientTransform="rotate(${angle})">
    <stop offset="0%" stop-color="${from}"/><stop offset="100%" stop-color="${to}"/>
  </linearGradient></defs>
  <rect width="${w}" height="${h}" fill="url(#g)"/>
  ${blobs}
  <text x="50%" y="50%" font-family="system-ui,-apple-system,Segoe UI,sans-serif" font-size="${Math.floor(Math.min(w, h) / 3.2)}"
        font-weight="700" fill="#ffffff" fill-opacity="0.92" text-anchor="middle" dominant-baseline="central">${initials}</text>
</svg>`;
}

router.get('/:name.svg', (req, res) => {
  const w = Math.min(Math.max(Number.parseInt(req.query.w ?? '600', 10) || 600, 32), 2000);
  const h = Math.min(Math.max(Number.parseInt(req.query.h ?? String(w), 10) || w, 32), 2000);
  const delay = Math.min(Number.parseInt(req.query.delay ?? '0', 10) || 0, 5000);

  const send = () => {
    res.type('image/svg+xml');
    res.set('Cache-Control', 'public, max-age=31536000, immutable');
    res.send(buildSvg(req.params.name, w, h));
  };
  if (delay) setTimeout(send, delay); else send();
});

export default router;
